name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Har kuni soat 00:00 da
  workflow_dispatch:

jobs:
  update:
    name: Update WakaTime stats in README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_OS: "True"
