name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once daily at 00:00 UTC
  workflow_dispatch:      # ✅ Add this to enable manual trigger

jobs:
  update-readme:
    name: Update WakaTime stats in README
    runs-on: ubuntu-latest

    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_OS: "true"
          SHOW_PROJECTS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_LINES_OF_CODE: "true"
